modLoader = "javafml"
loaderVersion = "*"
license = "CC BY-NC-ND 4.0"
issueTrackerURL = "https://github.com/Faboslav/structurify/issues"

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "${modAuthor}"
description = "${modDescription}"
logoFile = "icon.png"
logoBlur = false
displayURL = "https://www.curseforge.com/minecraft/mc-mods/structurify"

[[mixins]]
config = "structurify-forge.mixins.json"

[[mixins]]
config = "structurify-common.mixins.json"

[[dependencies.${ modId }]]
modId = "forge"
mandatory = true
versionRange = "[${forgeVersion},)"

[[dependencies.${ modId }]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"

[modproperties.${ modId }]
catalogueImageIcon = "catalogue_icon.png"
catalogueBackground = "catalogue_background.png"
configuredBackground = "catalogue_background.png"