modLoader = "javafml"
loaderVersion = "*"
license = "CC-BY-NC-ND-4.0"
issueTrackerURL = "https://github.com/Faboslav/structurify/issues"

[[mods]]
modId = "structurify"
version = "1.0.0"
displayName = "structurify"
authors = "fabo"
description = "tbd"
logoFile = "icon.png"
logoBlur = false
displayURL = "https://www.curseforge.com/minecraft/mc-mods/structurify"