name: "Build"

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"
            - "!master"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        name: Run build
        timeout-minutes: 30
        outputs:
            matrix: ${{ steps.set-matrix.outputs.matrix }}

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: "Set up JDK"
                uses: actions/setup-java@v4
                with:
                    java-version: 21
                    distribution: temurin

            -   name: "Setup Gradle and run build"
                uses: gradle/actions/setup-gradle@v3
                with:
                    cache-write-only: true
                    gradle-version: wrapper
                    arguments: build

            -   name: "Generate matrix for the run job"
                id: set-matrix
                run: ./.github/scripts/generate-run-matrix.sh
                

    run:
        runs-on: ubuntu-latest
        needs: build
        strategy:
            fail-fast: false
            matrix: ${{fromJson(needs.build.outputs.matrix)}}

        name: Run ${{ matrix.mod_loader }} ${{ matrix.version }} ${{ matrix.script }}
        timeout-minutes: 30

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: "Set up JDK"
                uses: actions/setup-java@v4
                with:
                    java-version: 21
                    distribution: temurin

            -   name: "Setup Gradle and run build"
                uses: gradle/actions/setup-gradle@v3
                with:
                    cache-read-only: true
                    gradle-version: wrapper
                    arguments: ${{ matrix.mod_loader }}:${{ matrix.version }}:build

            -   name: "Accept eula"
                run: mkdir -p ${{ matrix.mod_loader }}/versions/${{ matrix.version }}/run && echo "eula=true" > versions/${{ matrix.mod_loader }}/${{ matrix.version }}/run/eula.txt

            -   name: Run ${{ matrix.mod_loader }} ${{ matrix.version }} ${{ matrix.script }}
                uses: modmuss50/xvfb-action@v1
                with:
                    run: ./.github/scripts/run-${{ matrix.script }}.sh ${{ matrix.mod_loader }}:${{ matrix.version }}
                    shell: bash
