name: "Build"

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - "**"
            - "!master"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false

        name: Run build
        timeout-minutes: 30

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: "Set up JDK"
                uses: actions/setup-java@v4
                with:
                    java-version: 21
                    distribution: temurin

            -   name: "Setup Gradle and run build"
                uses: gradle/actions/setup-gradle@3
                with:
                    cache-write-only: true
                    gradle-version: wrapper
                    arguments: build

    run:
        runs-on: ubuntu-latest
        needs: build
        strategy:
            fail-fast: false
            matrix:
                mod_loader: [ fabric, forge, neoforge ]
                version: [ 1.20.1, 1.20.2, 1.20.4, 1.20.6 ]
                script: [ client, server ]

        name: Run ${{ matrix.mod_loader }} ${{ matrix.version }} ${{ matrix.script }}
        timeout-minutes: 30

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: "Set up JDK"
                uses: actions/setup-java@v4
                with:
                    java-version: 21
                    distribution: temurin

            -   name: "Setup Gradle and run build"
                uses: gradle/actions/setup-gradle@3
                with:
                    cache-read-only: true
                    gradle-version: wrapper
                    arguments: ${{ matrix.mod_loader }}:${{ matrix.version }}:build

            -   name: "Check if the mod loader is supported"
                id: check-mod-loader
                run: |
                    if ./gradlew projects | grep -q "Project ':${{ matrix.mod_loader }}:${{ matrix.version }}'"; then
                        echo "Mod loader is supported"
                        echo "is_mod_loader_supported=true" >> $GITHUB_OUTPUT
                    else
                        echo "Mod loader is not supported"
                        echo "is_mod_loader_supported=false" >> $GITHUB_OUTPUT
                    fi

            -   name: "Accept eula"
                if: steps.check-mod-loader.outputs.is_mod_loader_supported == 'true'
                run: mkdir -p versions/${{ matrix.mod_loader }}/${{ matrix.version }}/run && echo "eula=true" > versions/${{ matrix.mod_loader }}/${{ matrix.version }}/run/eula.txt

            -   name: Run ${{ matrix.mod_loader }} ${{ matrix.version }} ${{ matrix.script }}
                if: steps.check-mod-loader.outputs.is_mod_loader_supported == 'true'
                uses: modmuss50/xvfb-action@v1
                with:
                    run: ./.github/scripts/run-${{ matrix.script }}.sh ${{ matrix.mod_loader }}:${{ matrix.version }}
                    shell: bash